# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sdr-z103"
BBFILE_PATTERN_sdr-z103 = "^${LAYERDIR}/"
BBFILE_PRIORITY_sdr-z103 = "7"

LAYERSERIES_COMPAT_sdr-z103 = "scarthgap"
