// FieldMesh firmware packet BRAM pumped endpoint.
//
// This wrapper binds the reusable packet BRAM endpoint to the bounded service
// pump. The host-facing side still writes binary descriptors and packet bytes;
// the PL side can drain queued descriptors autonomously for a bounded service
// budget without parsing descriptors in the pump.

`timescale 1ns/1ps

module fieldmesh_firmware_packet_bram_pumped_endpoint #(
    parameter RING_SLOTS = 16,
    parameter PACKET_STRIDE = 1536,
    parameter PL_SERVICE_SLOTS = 16,
    parameter ADDR_WIDTH = 16,
    parameter RX_PACKET_BASE = RING_SLOTS * PACKET_STRIDE
) (
    input  wire                  clk,
    input  wire                  rst,
    input  wire                  enable,

    input  wire                  desc_wr_valid,
    input  wire [1:0]            desc_wr_region,
    input  wire [15:0]           desc_wr_slot,
    input  wire [15:0]           desc_wr_word,
    input  wire [31:0]           desc_wr_data,
    input  wire [3:0]            desc_wr_strb,
    output wire                  desc_wr_ready,
    output wire                  desc_wr_error,

    input  wire                  desc_rd_valid,
    input  wire [1:0]            desc_rd_region,
    input  wire [15:0]           desc_rd_slot,
    input  wire [15:0]           desc_rd_word,
    output wire                  desc_rd_ready,
    output wire                  desc_rd_rvalid,
    output wire [31:0]           desc_rd_rdata,
    output wire                  desc_rd_error,

    input  wire                  packet_valid,
    input  wire                  packet_write,
    input  wire [ADDR_WIDTH-1:0] packet_addr,
    input  wire [31:0]           packet_wdata,
    input  wire [3:0]            packet_wstrb,
    output wire                  packet_ready,
    output wire                  packet_rvalid,
    output wire [31:0]           packet_rdata,
    output wire                  packet_error,

    input  wire                  pump_start,
    input  wire                  pump_stop,
    input  wire [15:0]           pump_service_budget,
    output wire                  pump_active,
    output wire                  pump_done,
    output wire                  pump_drained_empty,
    output wire                  pump_budget_exhausted,
    output wire                  pump_stopped,
    output wire                  pump_error_seen,

    output wire                  service_busy,
    output wire                  service_done,
    output wire                  service_empty,
    output wire                  service_accepted,
    output wire                  service_crc_error,
    output wire                  service_bounds_error,
    output wire                  service_bram_error,
    output wire [15:0]           service_copied_bytes,
    output wire [15:0]           service_selected_slot,
    output wire [15:0]           service_queued_count,
    output wire [31:0]           service_selected_word,

    output wire [31:0]           pump_services_started,
    output wire [31:0]           pump_services_completed,
    output wire [31:0]           pump_accepted_count,
    output wire [31:0]           pump_error_count,
    output wire [31:0]           pump_empty_count,
    output wire [31:0]           desc_write_count,
    output wire [31:0]           desc_read_count,
    output wire [31:0]           desc_publish_count,
    output wire [31:0]           desc_clear_count,
    output wire [31:0]           desc_bounds_error_count,
    output wire [31:0]           packet_a_access_count,
    output wire [31:0]           packet_b_access_count,
    output wire [31:0]           packet_bounds_error_count,
    output wire [31:0]           packet_collision_count,
    output wire [31:0]           bram_service_count,
    output wire [31:0]           bram_crc_error_count,
    output wire [31:0]           bram_bounds_error_count,
    output wire [31:0]           bram_error_count,
    output wire [31:0]           bram_empty_count
);

wire pump_service_start;

fieldmesh_firmware_packet_bram_endpoint #(
    .RING_SLOTS(RING_SLOTS),
    .PACKET_STRIDE(PACKET_STRIDE),
    .PL_SERVICE_SLOTS(PL_SERVICE_SLOTS),
    .ADDR_WIDTH(ADDR_WIDTH),
    .RX_PACKET_BASE(RX_PACKET_BASE)
) endpoint (
    .clk(clk),
    .rst(rst),
    .enable(enable),
    .desc_wr_valid(desc_wr_valid),
    .desc_wr_region(desc_wr_region),
    .desc_wr_slot(desc_wr_slot),
    .desc_wr_word(desc_wr_word),
    .desc_wr_data(desc_wr_data),
    .desc_wr_strb(desc_wr_strb),
    .desc_wr_ready(desc_wr_ready),
    .desc_wr_error(desc_wr_error),
    .desc_rd_valid(desc_rd_valid),
    .desc_rd_region(desc_rd_region),
    .desc_rd_slot(desc_rd_slot),
    .desc_rd_word(desc_rd_word),
    .desc_rd_ready(desc_rd_ready),
    .desc_rd_rvalid(desc_rd_rvalid),
    .desc_rd_rdata(desc_rd_rdata),
    .desc_rd_error(desc_rd_error),
    .packet_valid(packet_valid),
    .packet_write(packet_write),
    .packet_addr(packet_addr),
    .packet_wdata(packet_wdata),
    .packet_wstrb(packet_wstrb),
    .packet_ready(packet_ready),
    .packet_rvalid(packet_rvalid),
    .packet_rdata(packet_rdata),
    .packet_error(packet_error),
    .service_start(pump_service_start),
    .service_busy(service_busy),
    .service_done(service_done),
    .service_empty(service_empty),
    .service_accepted(service_accepted),
    .service_crc_error(service_crc_error),
    .service_bounds_error(service_bounds_error),
    .service_bram_error(service_bram_error),
    .service_copied_bytes(service_copied_bytes),
    .service_selected_slot(service_selected_slot),
    .service_queued_count(service_queued_count),
    .service_selected_word(service_selected_word),
    .desc_write_count(desc_write_count),
    .desc_read_count(desc_read_count),
    .desc_publish_count(desc_publish_count),
    .desc_clear_count(desc_clear_count),
    .desc_bounds_error_count(desc_bounds_error_count),
    .packet_a_access_count(packet_a_access_count),
    .packet_b_access_count(packet_b_access_count),
    .packet_bounds_error_count(packet_bounds_error_count),
    .packet_collision_count(packet_collision_count),
    .bram_service_count(bram_service_count),
    .bram_crc_error_count(bram_crc_error_count),
    .bram_bounds_error_count(bram_bounds_error_count),
    .bram_error_count(bram_error_count),
    .bram_empty_count(bram_empty_count)
);

fieldmesh_firmware_service_pump service_pump (
    .clk(clk),
    .rst(rst),
    .enable(enable),
    .pump_start(pump_start),
    .pump_stop(pump_stop),
    .service_budget(pump_service_budget),
    .queued_count(service_queued_count),
    .service_busy(service_busy),
    .service_done(service_done),
    .service_empty(service_empty),
    .service_accepted(service_accepted),
    .service_crc_error(service_crc_error),
    .service_bounds_error(service_bounds_error),
    .service_bram_error(service_bram_error),
    .service_start(pump_service_start),
    .active(pump_active),
    .done(pump_done),
    .drained_empty(pump_drained_empty),
    .budget_exhausted(pump_budget_exhausted),
    .stopped(pump_stopped),
    .error_seen(pump_error_seen),
    .services_started(pump_services_started),
    .services_completed(pump_services_completed),
    .accepted_count(pump_accepted_count),
    .error_count(pump_error_count),
    .empty_count(pump_empty_count)
);

endmodule
