#!/usr/bin/env python3
"""Generate or run a guarded board-local FieldMesh RF TX guard preflight."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import time
from pathlib import Path
from typing import Any


EXPECTED_EVENT = "sdk_daemon_rf_tx_guard_plan"
EXPECTED_GUARD = "fieldmesh_iq_tx_guard"
EXPECTED_ENGINE = "fieldmesh_rf_packet_engine"


def load_ndjson(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise SystemExit(f"{path}:{line_no}: invalid JSON: {exc}") from exc
        if not isinstance(row, dict):
            raise SystemExit(f"{path}:{line_no}: expected JSON object")
        rows.append(row)
    return rows


def one_event(rows: list[dict[str, Any]], event: str) -> dict[str, Any]:
    matches = [row for row in rows if row.get("event") == event]
    if len(matches) != 1:
        raise SystemExit(f"expected exactly one {event} event, got {len(matches)}")
    return matches[0]


def require_guard_plan(rows: list[dict[str, Any]]) -> dict[str, Any]:
    plan = one_event(rows, EXPECTED_EVENT)
    if plan.get("guard_name") != EXPECTED_GUARD:
        raise SystemExit(f"expected guard {EXPECTED_GUARD}")
    if plan.get("rf_engine") != EXPECTED_ENGINE:
        raise SystemExit(f"expected RF engine {EXPECTED_ENGINE}")
    if plan.get("adapter_name") != "swarm0":
        raise SystemExit("RF TX guard plan must target swarm0")
    for key in (
        "requires_conducted_or_shielded",
        "requires_legal_frequency_profile",
        "requires_rx_first",
        "requires_sidecar_preflight",
        "requires_rf_packet_engine",
        "requires_tx_enable_guard",
        "schedules_exact_tx",
        "dry_run",
        "rollback_available",
    ):
        if plan.get(key) != 1:
            raise SystemExit(f"RF TX guard plan key {key} must be 1")
    for key in (
        "sets_tx_enable",
        "sets_tx_armed",
        "live_arm_requested",
        "live_arm_authorized",
        "hardware_writes_requested",
        "hardware_writes_authorized",
        "uses_iio",
        "uses_inter_board_ip_routing",
        "starts_rf_tx",
        "writes_hardware",
        "commands_executed",
    ):
        if plan.get(key) != 0:
            raise SystemExit(f"RF TX guard plan key {key} must be 0")
    return plan


def require_safety(args: argparse.Namespace, plan: dict[str, Any]) -> None:
    del plan
    if not args.conducted_or_shielded:
        raise SystemExit("--conducted-or-shielded is required")
    if not args.legal_frequency_profile:
        raise SystemExit("--legal-frequency-profile is required")
    if not args.rx_first:
        raise SystemExit("--rx-first is required")
    if not args.tx_enable_guard:
        raise SystemExit("--tx-enable-guard is required")
    if not args.sidecar_preflight_passed:
        raise SystemExit("--sidecar-preflight-passed is required")
    if not args.rf_engine_ready:
        raise SystemExit("--rf-engine-ready is required")
    if args.execute_live_preflight and not args.target_is_zynq_board:
        raise SystemExit("--execute-live-preflight requires --target-is-zynq-board")


def shell_quote(argv: list[str]) -> str:
    return " ".join(shlex.quote(arg) for arg in argv)


def command_row(name: str, argv: list[str], *, allow_failure: bool = False) -> dict[str, Any]:
    return {
        "name": name,
        "argv": argv,
        "shell": shell_quote(argv),
        "allow_failure": allow_failure,
    }


def build_rows(plan: dict[str, Any]) -> list[dict[str, Any]]:
    del plan
    return [
        command_row("pre_check_uid", ["id", "-u"]),
        command_row("pre_check_device_tree", ["test", "-d", "/proc/device-tree"]),
        command_row("pre_check_dev_mem", ["test", "-c", "/dev/mem"], allow_failure=True),
        command_row(
            "pre_check_fieldmesh_ctrl",
            ["sh", "-c", "find /proc/device-tree -iname '*fieldmesh*' -o -iname '*sidecar*' | head -20"],
            allow_failure=True,
        ),
        command_row(
            "pre_check_uio",
            ["sh", "-c", "ls -1 /sys/class/uio 2>/dev/null || true"],
            allow_failure=True,
        ),
        command_row(
            "pre_check_iio",
            ["sh", "-c", "ls -1 /sys/bus/iio/devices 2>/dev/null | head -20 || true"],
            allow_failure=True,
        ),
    ]


def write_script(path: Path, rows: list[dict[str, Any]], plan: dict[str, Any]) -> None:
    lines = [
        "#!/bin/sh",
        "set -eu",
        "",
        "# Generated by fieldmesh_rf_tx_guard_run.py for the Zynq board shell.",
        "# This script is a read-only preflight for the post-symbolizer TX guard.",
        "# It must not set TX enable, arm TX, write hardware, or start RF TX.",
        "",
        f"echo guard_name={shlex.quote(str(plan['guard_name']))}",
        f"echo rf_engine={shlex.quote(str(plan['rf_engine']))}",
        f"echo adapter_name={shlex.quote(str(plan['adapter_name']))}",
        f"echo dst_device_eui={shlex.quote(str(plan['dst_device_eui']))}",
        f"echo slot_epoch={int(plan['slot_epoch'])}",
        f"echo slot_index={int(plan['slot_index'])}",
        f"echo arm_window_us={int(plan['arm_window_us'])}",
        "",
        "# Read-only pre-state checks",
    ]
    for row in rows:
        suffix = " || true" if row["allow_failure"] else ""
        lines.append(f"{row['shell']}{suffix}")
    lines.extend(
        [
            "",
            "echo fieldmesh_rf_tx_guard_preflight=ok",
            "echo sets_tx_enable=0",
            "echo sets_tx_armed=0",
            "echo writes_hardware=0",
            "echo starts_rf_tx=0",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)


def run_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for row in rows:
        started = time.monotonic()
        proc = subprocess.run(
            row["argv"],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        ok = proc.returncode == 0 or row["allow_failure"]
        results.append(
            {
                "name": row["name"],
                "returncode": proc.returncode,
                "ok": ok,
                "elapsed_ms": int((time.monotonic() - started) * 1000),
                "stdout": proc.stdout.decode("utf-8", "replace")[:4096],
                "stderr": proc.stderr.decode("utf-8", "replace")[:4096],
            }
        )
        if not ok:
            break
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--daemon-query", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--conducted-or-shielded", action="store_true")
    parser.add_argument("--legal-frequency-profile", action="store_true")
    parser.add_argument("--rx-first", action="store_true")
    parser.add_argument("--tx-enable-guard", action="store_true")
    parser.add_argument("--sidecar-preflight-passed", action="store_true")
    parser.add_argument("--rf-engine-ready", action="store_true")
    parser.add_argument("--execute-live-preflight", action="store_true")
    parser.add_argument("--target-is-zynq-board", action="store_true")
    parser.add_argument("--pretty", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = load_ndjson(args.daemon_query)
    plan = require_guard_plan(rows)
    require_safety(args, plan)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    commands = build_rows(plan)
    script_path = args.out_dir / "fieldmesh_rf_tx_guard_preflight.sh"
    write_script(script_path, commands, plan)

    execution_results: list[dict[str, Any]] = []
    if args.execute_live_preflight:
        execution_results = run_rows(commands)

    report = {
        "event": "fieldmesh_rf_tx_guard_run",
        "ok": not execution_results or all(row["ok"] for row in execution_results),
        "mode": "execute-live-preflight" if args.execute_live_preflight else "dry-run",
        "adapter_name": plan["adapter_name"],
        "rf_engine": plan["rf_engine"],
        "guard_name": plan["guard_name"],
        "dst_device_eui": plan["dst_device_eui"],
        "traffic_class": plan["traffic_class"],
        "mode_id": plan["mode"],
        "route_kind": plan["route_kind"],
        "stream_id": plan["stream_id"],
        "sequence": plan["sequence"],
        "slot_epoch": plan["slot_epoch"],
        "slot_index": plan["slot_index"],
        "arm_window_us": plan["arm_window_us"],
        "generated_script": str(script_path),
        "commands": commands,
        "safety": {
            "conducted_or_shielded": bool(args.conducted_or_shielded),
            "legal_frequency_profile": bool(args.legal_frequency_profile),
            "rx_first": bool(args.rx_first),
            "tx_enable_guard": bool(args.tx_enable_guard),
            "sidecar_preflight_passed": bool(args.sidecar_preflight_passed),
            "rf_engine_ready": bool(args.rf_engine_ready),
            "target_is_zynq_board": bool(args.target_is_zynq_board),
            "executes_commands": bool(args.execute_live_preflight),
            "sets_tx_enable": False,
            "sets_tx_armed": False,
            "writes_hardware": False,
            "starts_rf_tx": False,
            "uses_iio": False,
            "uses_inter_board_ip_routing": False,
        },
        "guard_plan": plan,
        "execution_results": execution_results,
    }
    report_path = args.out_dir / "fieldmesh_rf_tx_guard_run.json"
    text = (
        json.dumps(report, indent=2, sort_keys=True)
        if args.pretty
        else json.dumps(report, sort_keys=True, separators=(",", ":"))
    )
    report_path.write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
