#!/usr/bin/env python3
"""Generate or execute a guarded board-local FieldMesh swarm0 TUN apply script."""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import time
from pathlib import Path
from typing import Any


EXPECTED_ADAPTER = "swarm0"


def load_ndjson(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise SystemExit(f"{path}:{line_no}: invalid JSON: {exc}") from exc
        if not isinstance(row, dict):
            raise SystemExit(f"{path}:{line_no}: expected JSON object")
        rows.append(row)
    return rows


def one_event(rows: list[dict[str, Any]], event: str) -> dict[str, Any]:
    matches = [row for row in rows if row.get("event") == event]
    if len(matches) != 1:
        raise SystemExit(f"expected exactly one {event} event, got {len(matches)}")
    return matches[0]


def require_tun_report(rows: list[dict[str, Any]]) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any], dict[str, Any]]:
    plan = one_event(rows, "sdk_tun_gateway_plan")
    commands = [row for row in rows if row.get("event") == "sdk_tun_gateway_command"]
    apply = one_event(rows, "sdk_tun_gateway_apply")
    rollback = one_event(rows, "sdk_tun_gateway_rollback_command")

    if plan.get("adapter_name") != EXPECTED_ADAPTER:
        raise SystemExit(f"expected adapter {EXPECTED_ADAPTER}")
    if plan.get("creates_tun_on_board") != 1 or plan.get("creates_tun_on_host") != 0:
        raise SystemExit("TUN plan must create the interface only on the board")
    for key in ("uses_tap", "uses_iio", "uses_inter_board_ip_routing"):
        if plan.get(key) != 0:
            raise SystemExit(f"TUN plan safety key {key} must be 0")
    if plan.get("requires_cap_net_admin") != 1:
        raise SystemExit("TUN plan must require CAP_NET_ADMIN")
    if apply.get("accepted") != 1 or apply.get("dry_run") != 1:
        raise SystemExit("TUN apply event must be an accepted dry-run validation")
    for key in ("live_writes_requested", "live_writes_authorized", "commands_executed", "writes_network"):
        if apply.get(key) != 0:
            raise SystemExit(f"TUN apply dry-run key {key} must be 0")
    if rollback.get("command") != "ip link delete swarm0":
        raise SystemExit("unexpected rollback command")
    if len(commands) != int(plan.get("command_count", -1)):
        raise SystemExit("TUN command count does not match plan")
    return plan, sorted(commands, key=lambda row: int(row.get("order", 0))), apply, rollback


def shell_quote(args: list[str]) -> str:
    return " ".join(shlex.quote(arg) for arg in args)


def split_command(command: str) -> list[str]:
    try:
        return shlex.split(command)
    except ValueError as exc:
        raise SystemExit(f"invalid shell command {command!r}: {exc}") from exc


def command_row(name: str, command: str, *, allow_failure: bool = False) -> dict[str, Any]:
    argv = split_command(command)
    return {
        "name": name,
        "argv": argv,
        "shell": shell_quote(argv),
        "allow_failure": allow_failure,
    }


def build_script_rows(
    plan: dict[str, Any],
    commands: list[dict[str, Any]],
    rollback: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    adapter = str(plan["adapter_name"])
    remote_cidr = str(plan["remote_mesh_cidr"])
    pre_state = [
        command_row("pre_check_uid", "id -u"),
        command_row("pre_check_tun_device", "test -c /dev/net/tun"),
        command_row("pre_link_state", f"ip -json link show {adapter}", allow_failure=True),
        command_row("pre_addr_state", f"ip -json addr show dev {adapter}", allow_failure=True),
        command_row("pre_route_state", f"ip route show {remote_cidr}", allow_failure=True),
    ]
    apply_rows = [
        command_row(f"apply_{int(row['order']):02d}", str(row["command"]))
        for row in commands
    ]
    rollback_rows = [
        command_row("rollback_delete_tun", str(rollback["command"]), allow_failure=True)
    ]
    return pre_state, apply_rows, rollback_rows


def write_script(
    path: Path,
    pre_state: list[dict[str, Any]],
    apply_rows: list[dict[str, Any]],
    rollback_rows: list[dict[str, Any]],
) -> None:
    lines = [
        "#!/bin/sh",
        "set -eu",
        "",
        "# Generated by fieldmesh_tun_apply_run.py. Intended for the Zynq board shell.",
        "# Review the board identity and route plan before running with network-write approval.",
        "",
        "if [ \"$(id -u)\" != \"0\" ]; then",
        "  echo 'must run as root for CAP_NET_ADMIN-style TUN setup' >&2",
        "  exit 1",
        "fi",
        "if [ ! -c /dev/net/tun ]; then",
        "  if grep -qw tun /proc/misc 2>/dev/null; then",
        "    mkdir -p /dev/net",
        "    mknod /dev/net/tun c 10 200 2>/dev/null || true",
        "  fi",
        "fi",
        "if [ ! -c /dev/net/tun ]; then",
        "  echo '/dev/net/tun is missing; enable CONFIG_TUN in the board kernel' >&2",
        "  exit 127",
        "fi",
        "",
        "# Pre-state capture",
    ]
    for row in pre_state:
        suffix = " || true" if row["allow_failure"] else ""
        lines.append(f"{row['shell']}{suffix}")
    lines.extend(["", "# Apply", "trap 'ip link delete swarm0 >/dev/null 2>&1 || true' ERR"])
    for row in apply_rows:
        lines.append(row["shell"])
    lines.extend(["trap - ERR", "", "# Rollback command if needed"])
    for row in rollback_rows:
        lines.append(f"# {row['shell']}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)


def require_live_guard(args: argparse.Namespace) -> None:
    if args.execute_live_network and not args.allow_network_writes:
        raise SystemExit("--execute-live-network requires --allow-network-writes")
    if args.execute_live_network and not args.target_is_zynq_board:
        raise SystemExit("--execute-live-network requires --target-is-zynq-board")
    if args.execute_live_network and not args.cap_net_admin_confirmed:
        raise SystemExit("--execute-live-network requires --cap-net-admin-confirmed")


def run_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for row in rows:
        started = time.monotonic()
        proc = subprocess.run(
            row["argv"],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        elapsed_ms = int((time.monotonic() - started) * 1000)
        ok = proc.returncode == 0 or row["allow_failure"]
        results.append(
            {
                "name": row["name"],
                "returncode": proc.returncode,
                "ok": ok,
                "elapsed_ms": elapsed_ms,
                "stdout": proc.stdout.decode("utf-8", "replace")[:4096],
                "stderr": proc.stderr.decode("utf-8", "replace")[:4096],
            }
        )
        if not ok:
            break
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tun-gateway-report", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--execute-live-network", action="store_true")
    parser.add_argument("--allow-network-writes", action="store_true")
    parser.add_argument("--target-is-zynq-board", action="store_true")
    parser.add_argument("--cap-net-admin-confirmed", action="store_true")
    parser.add_argument("--pretty", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    require_live_guard(args)
    rows = load_ndjson(args.tun_gateway_report)
    plan, commands, apply, rollback = require_tun_report(rows)
    pre_state, apply_rows, rollback_rows = build_script_rows(plan, commands, rollback)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    script_path = args.out_dir / "fieldmesh_tun_apply.sh"
    write_script(script_path, pre_state, apply_rows, rollback_rows)

    executed: list[dict[str, Any]] = []
    if args.execute_live_network:
        executed = run_rows(pre_state + apply_rows)

    report = {
        "event": "fieldmesh_tun_apply_run",
        "ok": True,
        "mode": "execute-live-network" if args.execute_live_network else "dry-run",
        "adapter_name": plan["adapter_name"],
        "local_mesh_ip": plan["local_mesh_ip"],
        "remote_mesh_cidr": plan["remote_mesh_cidr"],
        "dst_device_eui": plan["dst_device_eui"],
        "route_kind": plan["route_kind"],
        "selected_mode": plan["selected_mode"],
        "generated_script": str(script_path),
        "pre_state_commands": pre_state,
        "apply_commands": apply_rows,
        "rollback_commands": rollback_rows,
        "safety": {
            "executes_commands": bool(args.execute_live_network),
            "writes_network": bool(args.execute_live_network),
            "allow_network_writes": bool(args.allow_network_writes),
            "target_is_zynq_board": bool(args.target_is_zynq_board),
            "cap_net_admin_confirmed": bool(args.cap_net_admin_confirmed),
            "uses_iio": False,
            "uses_tap": False,
            "uses_inter_board_ip_routing": False,
        },
        "sdk_apply": apply,
        "execution_results": executed,
    }
    if executed and not all(row["ok"] for row in executed):
        report["ok"] = False

    report_path = args.out_dir / "fieldmesh_tun_apply_run.json"
    text = (
        json.dumps(report, indent=2, sort_keys=True)
        if args.pretty
        else json.dumps(report, sort_keys=True, separators=(",", ":"))
    )
    report_path.write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
