#!/usr/bin/env python3
"""Generate checked FieldMesh Vivado sidecar overlay scaffold files."""

from __future__ import annotations

import argparse
import io
import json
from contextlib import redirect_stdout
from pathlib import Path

import fieldmesh_sidecar_plan as sidecar_plan
import fieldmesh_vendor_dma_inventory as inventory


def render_tcl(plan: dict) -> str:
    buffer = io.StringIO()
    with redirect_stdout(buffer):
        sidecar_plan.emit_tcl(plan)
    return buffer.getvalue()


def render_readme(plan: dict) -> str:
    blocks = "\n".join(
        f"- `{block['name']}` at `{block['address']}` size `0x{int(block['size']):04X}` IRQ `{block['irq']}`"
        for block in plan["sidecar_blocks"]
    )
    rtl = "\n".join(f"- `{row['path']}`" for row in plan["required_rtl_status"]["files"])
    variants = "\n".join(
        f"- `{row['variant']}`: sidecar={'ok' if row['sidecar']['ok'] else 'conflict'}, "
        f"hp_policy={'ok' if row['hp_policy']['ok'] else 'conflict'}"
        for row in plan["variants"]
    )
    return f"""# FieldMesh Vivado Overlay Scaffold

This directory is generated by `tools/fieldmesh_vivado_overlay_scaffold.py`.
It is a preflight artifact for the later Vivado overlay patch. It does not
modify the imported Pluto HDL tree.

## Sidecar Blocks

{blocks}

## Required RTL

{rtl}

## Variant Checks

{variants}

## Files

- `fieldmesh_sidecar_plan.json` - machine-readable checked plan.
- `fieldmesh_sidecar_constants.tcl` - Tcl constants and required RTL list.
- `fieldmesh_required_rtl.f` - absolute Verilog file list for compile/build tooling.
- `fieldmesh_bd_overlay_stub.tcl` - non-mutating Vivado Tcl scaffold with the
  intended insertion points and policy checks.
"""


def render_stub(plan: dict, repo_root: Path) -> str:
    hp = plan["memory_port_policy"]
    return f"""# FieldMesh Vivado sidecar overlay scaffold.
# Generated by tools/fieldmesh_vivado_overlay_scaffold.py.
#
# This file is intentionally non-mutating. It documents the checked insertion
# points for a later real Vivado overlay Tcl. Do not source it expecting a block
# design change.

source [file join [file dirname [info script]] fieldmesh_sidecar_constants.tcl]

# Repository root used when this scaffold was generated:
set FIELDMESH_REPO_ROOT {{{repo_root}}}

# Required RTL files for the later overlay:
# foreach rtl $fieldmesh_required_rtl {{
#   add_files -norecurse [file join $FIELDMESH_REPO_ROOT $rtl]
# }}

# Current policy:
# - Keep ADI RX samples on {hp["keep_adi_rx_samples"]}.
# - Keep ADI TX samples on {hp["keep_adi_tx_samples"]}.
# - Prefer FieldMesh RX/S2MM packet DMA on {hp["prefer_fieldmesh_rx_s2mm"]}.
# - Prefer FieldMesh TX/MM2S packet DMA on {hp["prefer_fieldmesh_tx_mm2s"]}.

# Later real overlay outline:
# 1. Enable the additional PS HP ports needed for packet DMA:
#    ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP0 1
#    ad_ip_parameter sys_ps7 CONFIG.PCW_USE_S_AXI_HP3 1
# 2. Add the FieldMesh RTL files above to the project.
# 3. Instantiate fieldmesh_sidecar_ctrl_axi_lite as fieldmesh_ctrl at
#    $FIELDMESH_CTRL_BASE and connect its irq to $FIELDMESH_CTRL_IRQ.
# 4. Instantiate fieldmesh_sidecar_axis_bridge as the byte-only packet transport
#    boundary between sidecar DMA/IIO blocks and FieldMesh packet streams.
# 5. Instantiate fieldmesh_axis16_byte_adapter when using ADI axi_dmac, because
#    that DMA IP requires 16-bit-or-wider stream ports while FieldMesh stays
#    byte-oriented.
# 6. Instantiate sidecar packet DMA controls at $FIELDMESH_TX_DMA_BASE and
#    $FIELDMESH_RX_DMA_BASE, or keep the first overlay AXI-lite/FIFO-only.
# 7. For the non-transmitting RF-engine overlay, feed the parsed TX packet
#    stream through fieldmesh_bpsk_iq_symbolizer and fieldmesh_iq_tx_guard,
#    but keep the guard unarmed and leave its IQ output parked.
# 8. Do not modify axi_ad9361_adc_dma at 0x7C400000 or axi_ad9361_dac_dma at
#    0x7C420000 in the first FieldMesh overlay.
"""


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--variant",
        action="append",
        type=inventory.parse_variant,
        required=True,
        metavar="NAME=SYSTEM_BD_TCL",
        help="variant name and Vivado system_bd.tcl path; repeat for comparisons",
    )
    parser.add_argument("--repo-root", type=Path, default=Path.cwd(), help="repository root for RTL checks")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(".config/fieldmesh/vivado-overlay-scaffold"),
        help="directory for generated scaffold files",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    out_dir = args.out_dir
    plan = sidecar_plan.build_plan(
        args.variant,
        check_sidecar=True,
        repo_root=repo_root,
        check_rtl=True,
        check_hp_policy=True,
    )
    if not plan["ok"]:
        return 1

    absolute_rtl = [str(repo_root / row["path"]) for row in plan["required_rtl_status"]["files"]]
    write(out_dir / "fieldmesh_sidecar_plan.json", json.dumps(plan, indent=2, sort_keys=True) + "\n")
    write(out_dir / "fieldmesh_sidecar_constants.tcl", render_tcl(plan))
    write(out_dir / "fieldmesh_required_rtl.f", "\n".join(absolute_rtl) + "\n")
    write(out_dir / "fieldmesh_bd_overlay_stub.tcl", render_stub(plan, repo_root))
    write(out_dir / "README.md", render_readme(plan))
    print(f"fieldmesh_overlay_scaffold={out_dir}")
    print(f"required_rtl={len(absolute_rtl)}")
    print("ok=true")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
