#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="$repo_root/resources/source-index"
out="$out_dir/pluto-archive-inventory.md"

archive_1r1t="/mnt/c/baidunetdiskdownload/SDR-Z203/04源码与文档/pluto/plutosdr-fw-1r1t.zip"
archive_2r2t="/mnt/c/baidunetdiskdownload/SDR-Z203/04源码与文档/pluto/plutosdr-fw-2r2t.zip"

mkdir -p "$out_dir"

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "missing archive: $path" >&2
    exit 1
  fi
}

list_paths() {
  local archive="$1"
  7z l -slt "$archive" | awk -F' = ' '/^Path = / { print $2 }'
}

source_focus() {
  rg '(^plutosdr-fw/(Makefile|README\.md|LICENSE\.md|setup_env\.sh|download_and_test\.sh|\.gitmodules)$|^plutosdr-fw/scripts/[^/]+$|^plutosdr-fw/hdl/projects/pluto/[^/]+$|^plutosdr-fw/linux/arch/arm/boot/dts/(zynq-pluto|zynq-sidekiqz2|adi-fmcomms2|adi-adrv9361|adi-adrv9364)|^plutosdr-fw/buildroot/board/pluto/[^/]+$|^plutosdr-fw/u-boot-xlnx/configs/zynq_pluto)' "$1" \
    | sort -u
}

generated_outputs() {
  rg '(^plutosdr-fw/build/(boot|pluto|uboot|u-boot|rootfs|zImage|uImage|system_top|zynq).*|^plutosdr-fw/build_sdimg/)' "$1" \
    | sort -u
}

archive_size() {
  stat -c '%s bytes' "$1"
}

section_for_archive() {
  local label="$1"
  local archive="$2"
  local tmp
  tmp="$(mktemp)"
  list_paths "$archive" > "$tmp"

  {
    echo "## $label"
    echo
    echo "- External archive: \`$archive\`"
    echo "- Archive size: \`$(archive_size "$archive")\`"
    echo "- Path count: \`$(wc -l < "$tmp" | tr -d ' ')\`"
    echo
    echo "### Top-Level Source Tree"
    echo
    awk -F/ '$1 == "plutosdr-fw" && NF >= 2 && $2 != "" { print "- `" $2 "`" }' "$tmp" | sort -u
    echo
    echo "### Key Build Inputs"
    echo
    source_focus "$tmp" | sed 's/^/- `/' | sed 's/$/`/'
    echo
    echo "### Generated Firmware Outputs Present In Archive"
    echo
    generated_outputs "$tmp" | sed 's/^/- `/' | sed 's/$/`/'
    echo
  } >> "$out"

  rm -f "$tmp"
}

compare_focused_paths() {
  local tmp1 tmp2 focus1 focus2
  tmp1="$(mktemp)"
  tmp2="$(mktemp)"
  focus1="$(mktemp)"
  focus2="$(mktemp)"

  list_paths "$archive_1r1t" > "$tmp1"
  list_paths "$archive_2r2t" > "$tmp2"
  source_focus "$tmp1" > "$focus1"
  source_focus "$tmp2" > "$focus2"

  {
    echo "## Focused Path Differences"
    echo
    echo "This compares only the focused build-input path set above, not every file in"
    echo "the generated build trees."
    echo
    echo "### Present Only In 1R1T Archive"
    echo
    comm -23 "$focus1" "$focus2" | sed 's/^/- `/' | sed 's/$/`/' || true
    echo
    echo "### Present Only In 2R2T Archive"
    echo
    comm -13 "$focus1" "$focus2" | sed 's/^/- `/' | sed 's/$/`/' || true
    echo
  } >> "$out"

  rm -f "$tmp1" "$tmp2" "$focus1" "$focus2"
}

require_file "$archive_1r1t"
require_file "$archive_2r2t"

{
  echo "# Pluto Firmware Source Archive Inventory"
  echo
  echo "Generated by \`tools/index_pluto_archives.sh\`."
  echo
  echo "The original Pluto firmware source archives are multi-gigabyte zip files and"
  echo "are intentionally kept outside this repo. This inventory captures enough"
  echo "structure to plan builds and compare 1R1T/2R2T inputs without extracting the"
  echo "full trees."
  echo
} > "$out"

section_for_archive "plutosdr-fw-1r1t.zip" "$archive_1r1t"
section_for_archive "plutosdr-fw-2r2t.zip" "$archive_2r2t"
compare_focused_paths

echo "Wrote $out"
