#!/bin/sh
set -eu

# Generated by fieldmesh_rf_tx_guard_run.py for the Zynq board shell.
# This script is a read-only preflight for the post-symbolizer TX guard.
# It must not set TX enable, arm TX, write hardware, or start RF TX.

echo guard_name=fieldmesh_iq_tx_guard
echo rf_engine=fieldmesh_rf_packet_engine
echo adapter_name=swarm0
echo dst_device_eui=020000000103
echo slot_epoch=0
echo slot_index=3
echo arm_window_us=5000

# Read-only pre-state checks
id -u
test -d /proc/device-tree
test -c /dev/mem || true
sh -c 'find /proc/device-tree -iname '"'"'*fieldmesh*'"'"' -o -iname '"'"'*sidecar*'"'"' | head -20' || true
sh -c 'ls -1 /sys/class/uio 2>/dev/null || true' || true
sh -c 'ls -1 /sys/bus/iio/devices 2>/dev/null | head -20 || true' || true

echo fieldmesh_rf_tx_guard_preflight=ok
echo sets_tx_enable=0
echo sets_tx_armed=0
echo writes_hardware=0
echo starts_rf_tx=0
