#!/bin/sh
set -eu

# Generated by fieldmesh_tun_apply_run.py. Intended for the Zynq board shell.
# Review the board identity and route plan before running with network-write approval.

if [ "$(id -u)" != "0" ]; then
  echo 'must run as root for CAP_NET_ADMIN-style TUN setup' >&2
  exit 1
fi
if [ ! -c /dev/net/tun ]; then
  if grep -qw tun /proc/misc 2>/dev/null; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200 2>/dev/null || true
  fi
fi
if [ ! -c /dev/net/tun ]; then
  echo '/dev/net/tun is missing; enable CONFIG_TUN in the board kernel' >&2
  exit 127
fi

# Pre-state capture
id -u
test -c /dev/net/tun
ip -json link show swarm0 || true
ip -json addr show dev swarm0 || true
ip route show 10.77.2.0/24 || true

# Apply
trap 'ip link delete swarm0 >/dev/null 2>&1 || true' ERR
ip tuntap add dev swarm0 mode tun
ip addr add 10.77.1.1/16 dev swarm0
ip link set swarm0 mtu 1200 up
ip route add 10.77.2.0/24 dev swarm0
trap - ERR

# Rollback command if needed
# ip link delete swarm0
